services:
  homeassistant:
    image: homeassistant/home-assistant:2024.10.1@sha256:f881515cefc888b91a0098cb64a22fa586aa863562aa07dcf9b87546bad5623f
    volumes:
      - ./docker-compose/hass/configuration.yaml:/config/configuration.yaml
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8123:8123

  mosquitto:
    image: eclipse-mosquitto:2.0@sha256:069ab2a92ce87b318b91586845af1a53d762b7cffae60737e76e1a8f8dd19e11
    volumes:
      - "./docker-compose/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro"
      - "./docker-compose/mosquitto/acl.conf:/mosquitto/config/acl.conf:ro"
      - "./docker-compose/mosquitto/passwd:/mosquitto/config/passwd:ro"
    ports:
      - 1883

  mosquitto-debug:
    image: eclipse-mosquitto:2.0@sha256:069ab2a92ce87b318b91586845af1a53d762b7cffae60737e76e1a8f8dd19e11
    entrypoint: mosquitto_sub
    command:
      - --id
      - debug-all
      - --url
      - mqtt://hass:hass@mosquitto:1883/#
      - --verbose
    depends_on:
      - mosquitto

  rika-firenet-mock:
    build:
      context: https://github.com/jeremiehuchet/rika-firenet-api-rs.git#:mock
    ports:
      - 3000
    stop_signal: SIGKILL

  somfy-protect-mock:
    build:
      context: https://github.com/jeremiehuchet/somfy-protect-api-rs.git#:mock
    ports:
      - 3000
    stop_signal: SIGKILL

  hass-mqtt-bridge:
    build:
      context: ../
      dockerfile: end-to-end-testing/docker-compose/hass-mqtt-bridge/Dockerfile
    environment:
      RUST_LOG: info,hass_mqtt_bridge=debug
      MQTT_BROKER_URL: mqtt://mosquitto:1883
      MQTT_USERNAME: hass
      MQTT_PASSWORD: hass
      RIKA_BASEURL: http://rika-firenet-mock:3000
      RIKA_USERNAME: registered-user@rika-firenet.com
      RIKA_PASSWORD: secret
      #SOMFY_API_BASEURL: http://somfy-protect-mock:3000/api
      #SOMFY_AUTH_BASEURL: http://somfy-protect-mock:3000/auth
      #SOMFY_CLIENT_ID: somfy
      #SOMFY_CLIENT_SECRET: somfy secret
      #SOMFY_USERNAME: user@somfy.com
      #SOMFY_PASSWORD: user password
