services:
  homeassistant:
    image: homeassistant/home-assistant:2024.4
    volumes:
      - ./docker-compose/hass/configuration.yaml:/config/configuration.yaml
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8123:8123

  mosquitto:
    image: eclipse-mosquitto:2.0
    volumes:
      - "./docker-compose/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro"
      - "./docker-compose/mosquitto/acl.conf:/mosquitto/config/acl.conf:ro"
      - "./docker-compose/mosquitto/passwd:/mosquitto/config/passwd:ro"
    ports:
      - 1883:1883

  mosquitto-debug:
    image: eclipse-mosquitto:2.0
    entrypoint: mosquitto_sub
    command:
      - --id
      - debug-all
      - --url
      - mqtt://hass:hass@mosquitto:1883/#
      - --verbose
    depends_on:
      - mosquitto

  rika-firenet-mock:
    build:
      context: https://github.com/jeremiehuchet/rika-firenet-api-rs.git#:mock
    ports:
      - 3000:3000

  somfy-protect-mock:
    container_name: somfy-protect-mock
    build:
      context: https://github.com/jeremiehuchet/somfy-protect-api-rs.git#:mock
    ports:
      - 3001:3000

  hass-mqtt-bridge:
    build:
      context: ../
      dockerfile: end-to-end-testing/docker-compose/hass-mqtt-bridge/Dockerfile
    environment:
      RUST_LOG: info,hass_mqtt_bridge:debug
      MQTT_BROKER_URL: mqtt://mosquitto:1883
      MQTT_USERNAME: hass
      MQTT_PASSWORD: hass
      RIKA_BASEURL: http://rika-firenet-mock:3000
      RIKA_USERNAME: registered-user@rika-firenet.com
      RIKA_PASSWORD: secret
      SOMFY_API_BASEURL: http://somfy-protect-mock:3000/api
      SOMFY_AUTH_BASEURL: http://somfy-protect-mock:3000/auth
      SOMFY_CLIENT_ID: somfy
      SOMFY_CLIENT_SECRET: somfy secret
      SOMFY_USERNAME: user@somfy.com
      SOMFY_PASSWORD: user password
