services:
  homeassistant:
    image: homeassistant/home-assistant:2025.3.1@sha256:304e6999282c5512939db671e5fcbaa923a1f7c9a6e3990cb5baff7abcb9ac4b
    volumes:
      - ./docker-compose/hass/configuration.yaml:/config/configuration.yaml
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8123:8123

  mosquitto:
    image: eclipse-mosquitto:2.0@sha256:8b396cec28cd5e8e1a3aba1d9abdbddd42c454c80f703e77c1bec56e152fa54e
    volumes:
      - "./docker-compose/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro"
      - "./docker-compose/mosquitto/acl.conf:/mosquitto/config/acl.conf:ro"
      - "./docker-compose/mosquitto/passwd:/mosquitto/config/passwd:ro"
    ports:
      - 1883

  mosquitto-debug:
    image: eclipse-mosquitto:2.0@sha256:8b396cec28cd5e8e1a3aba1d9abdbddd42c454c80f703e77c1bec56e152fa54e
    entrypoint: mosquitto_sub
    command:
      - --id
      - debug-all
      - --url
      - mqtt://hass:hass@mosquitto:1883/#
      - --verbose
    depends_on:
      - mosquitto

  rika-firenet-mock:
    build:
      context: https://github.com/jeremiehuchet/rika-firenet-api-rs.git#:mock
    ports:
      - 3000
    stop_signal: SIGKILL

  somfy-protect-mock:
    build:
      context: https://github.com/jeremiehuchet/somfy-protect-api-rs.git#:mock
    ports:
      - 3000
    stop_signal: SIGKILL

  hass-mqtt-bridge:
    build:
      context: ../
      dockerfile: end-to-end-testing/docker-compose/hass-mqtt-bridge/Dockerfile
    environment:
      RUST_BACKTRACE: full
      RUST_LOG: info,hass_mqtt_bridge=debug
      MQTT_BROKER_URL: mqtt://mosquitto:1883
      MQTT_USERNAME: hass
      MQTT_PASSWORD: hass
      RIKA_BASEURL: http://rika-firenet-mock:3000
      RIKA_USERNAME: registered-user@rika-firenet.com
      RIKA_PASSWORD: secret
      RIKA_STOVE_DISCOVERY_REPEAT_INTERVAL: 4s..6s
      RIKA_STOVE_DISCOVERY_BACKOFF_CEIL: 3s
      RIKA_STOVE_STATUS_REPEAT_INTERVAL: 1s..2s
      RIKA_STOVE_STATUS_BACKOFF_CEIL: 5s
      #SOMFY_API_BASEURL: http://somfy-protect-mock:3000/api
      #SOMFY_AUTH_BASEURL: http://somfy-protect-mock:3000/auth
      #SOMFY_CLIENT_ID: somfy
      #SOMFY_CLIENT_SECRET: somfy secret
      #SOMFY_USERNAME: user@somfy.com
      #SOMFY_PASSWORD: user password
