name: Build and test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install tarball+https://install.devenv.sh/latest

      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv ci

      - uses: Swatinem/rust-cache@v2

      - name: Cargo test
        run: devenv shell cargo test

  playwright:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Build test stack
        working-directory: end-to-end-testing
        run: docker-compose build

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: end-to-end-testing/node_modules
          key: ${{ runner.os }}-nodemodules-${{ hashFiles('end-to-end-testing/pnpm-lock.yaml') }}

      - name: Install Playwright and dependencies
        working-directory: end-to-end-testing
        run: |
          corepack enable pnpm
          pnpm install --frozen-lockfile
          pnpm playwright install --with-deps firefox

      - name: Run Playwright tests
        working-directory: end-to-end-testing
        run: pnpm test

      - name: Archive Playwright report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: end-to-end-testing/playwright-report/
          retention-days: 30

      - name: Publish Test Results
        uses: mikepenz/action-junit-report@v4
        if: ${{ !cancelled() }}
        with:
          report_paths: end-to-end-testing/playwright-report/results.xml
