name: Build and test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
      - uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv ci

      - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2

      - name: Cargo test
        run: devenv shell cargo test

  playwright:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
      - uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Build test stack
        working-directory: end-to-end-testing
        run: |
          docker compose build
          docker compose pull

      - name: Cache node modules
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4
        with:
          path: end-to-end-testing/node_modules
          key: ${{ runner.os }}-nodemodules-${{ hashFiles('end-to-end-testing/pnpm-lock.yaml') }}

      - name: Run Playwright tests
        run: devenv shell end-to-end-tests

      - name: Archive Playwright report
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: end-to-end-testing/playwright-report/
          retention-days: 30

      - name: Publish Test Results
        uses: mikepenz/action-junit-report@992d97d6eb2e5f3de985fbf9df6a04386874114d # v5
        if: ${{ !cancelled() }}
        with:
          report_paths: end-to-end-testing/playwright-report/results.xml
